In [31]:
import pandas as pd
import numpy as np

In [32]:
df = pd.Series([2,3,5,3,6,46,2],index=["a", "b", "c", "d", "e", "f","h"])
df

a     2
b     3
c     5
d     3
e     6
f    46
h     2
dtype: int64

In [33]:
df = pd.Series([1,2,3,4,])
df

0    1
1    2
2    3
3    4
dtype: int64

In [34]:
#Empty Series

obj=pd.Series()
obj

Series([], dtype: object)

In [35]:
#Change Index

sam=pd.Series([1,2,3,4,5,6],index=["a", "b", "c", "d", "e","f"])
sam

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [36]:
obj=pd.Series(range(5,9),index=["a", "b", "c", "d",])
obj

a    5
b    6
c    7
d    8
dtype: int64

In [37]:
obj=pd.Series("Sameer")
obj

0    Sameer
dtype: object

In [38]:
a=[1,2,3,4,5]
b=[6,7,3,7,4]
pd.Series((a+b),index=["a", "b", "c", "d", "e", "f","g", "h","i", "j"])

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    3
i    7
j    4
dtype: int64

In [39]:
ls=pd.Series(range(4,9))
ls

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [40]:
ls = np.arange(2,30,4)
pd.Series(ls)

0     2
1     6
2    10
3    14
4    18
5    22
6    26
dtype: int64

In [41]:
obj = pd.Series({'a':1, 'b':2,'c':3,'d':4})
obj

a    1
b    2
c    3
d    4
dtype: int64

In [42]:
obj = pd.Series([1,2,3,4],index=["a","b","c","d"])
obj

a    1
b    2
c    3
d    4
dtype: int64

In [43]:
class12 = pd.Series({"Seca":41,"Srcb":43,"Secc:":43})
class12

Seca     41
Srcb     43
Secc:    43
dtype: int64

In [44]:
obj = pd.Series({"qtr1":500,"qte2":500})
obj

qtr1    500
qte2    500
dtype: int64

In [45]:
obj = pd.Series(5000,index= ["a", "b", "c", "d", "e", "f","g","h","i", "j"])
obj1 = pd.Series(4000,index=[1,2,3,4,5,6,7])
pd.Series(obj+obj1)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
i   NaN
j   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
dtype: float64

In [46]:
obj1 = pd.Series(4000,index=[1,2,3,4,5,6,7])
obj1

1    4000
2    4000
3    4000
4    4000
5    4000
6    4000
7    4000
dtype: int64

In [47]:
obj = pd.Series([4,6,3,6])
obj1 = pd.Series([5,7,6,7])
(obj+obj1)

0     9
1    13
2     9
3    13
dtype: int64

In [48]:
a=[1,2,3,4,5]
b=[6,7,3,7,4]
pd.Series(a+b)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    3
8    7
9    4
dtype: int64

In [49]:
ln = range(2020,2029,2)
pd.Series(ln)

0    2020
1    2022
2    2024
3    2026
4    2028
dtype: int64

In [50]:
ln = pd.Series(200,index=[2020,2022,2024,2026,2028])
ln

2020    200
2022    200
2024    200
2026    200
2028    200
dtype: int64

In [51]:
ln = pd.Series(200,index=range(2020,2029,2))
ln

2020    200
2022    200
2024    200
2026    200
2028    200
dtype: int64

In [52]:
obj = pd.Series([5,6,3,7,None,4])
obj

0    5.0
1    6.0
2    3.0
3    7.0
4    NaN
5    4.0
dtype: float64

In [53]:
obj = pd.Series([5,6,3,np.nan,6])
obj

0    5.0
1    6.0
2    3.0
3    NaN
4    6.0
dtype: float64

In [54]:
obj =  pd.Series([4,6,7,4,np.nan,4])
obj

0    4.0
1    6.0
2    7.0
3    4.0
4    NaN
5    4.0
dtype: float64

In [55]:
obj = pd.Series(["sam","ron",None,"peter"])
obj

0      sam
1      ron
2     None
3    peter
dtype: object

In [56]:
obj = pd.Series(["sam","ron",np.nan,"peter"])
obj

0      sam
1      ron
2      NaN
3    peter
dtype: object

In [57]:
data=[1200,2000,1300,4500]
data1=[100,200]
obj=pd.Series(data+data1,index=["a","b","c","d","e","f"])
obj

a    1200
b    2000
c    1300
d    4500
e     100
f     200
dtype: int64

In [191]:
ln = pd.Series(200,index=[2020,2022,2024,2026,2028])
ln

2020    200
2022    200
2024    200
2026    200
2028    200
dtype: int64

In [ ]:
ln = pd.Series(200,index=[2020,2022,2024,2026,2028].dtype=float)
ln

In [189]:
data=pd.Series([200])
obj=pd.Series((data),index=["a","b","c","d","e","f"])
obj

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
dtype: float64

In [ ]:
sec=pd.Series([100,600,700,700],index=["a","b","c","d"])
sec

a    100
b    600
c    700
d    700
dtype: int64

In [ ]:
sec=["a","b","c","d"]
cont=[500,300,500,800]
ls=pd.Series(cont,index=sec)
ls

a    500
b    300
c    500
d    800
dtype: int64

1
(6,)
6
48
object
['a' 'a' 'a' 'a' 'a' 'a']
Index([5, 6, 7, 8, 9, 10], dtype='int64')
False
False
None

In [66]:
import pandas as pd
import numpy as np

a=np.arange(5,11)
obj=pd.Series(a*a,index=a)
print(obj.ndim)
print(obj.shape)
print(obj.size)
print(obj.nbytes)
print(obj.dtype)
print(obj.values)
print(obj.index)
print(obj.hasnans)
print(obj.empty)
obj.name="sam"
print(obj.name)

1
(6,)
6
48
int64
[ 25  36  49  64  81 100]
Index([5, 6, 7, 8, 9, 10], dtype='int64')
False
False
sam

In [147]:
data=[1200,2000,1300,4500,451,65,48,485]
data[0:4]

[1200, 2000, 1300, 4500]

In [ ]:
data=[1200,2000,1300,4500,451,65,48,485]
data[3]=400
data

[1200, 2000, 1300, 400, 451, 65, 48, 485]

In [153]:
data=pd.Series([1200,2000,1300,4500,451,65,48,485])
data[0::3]=400
data

0     400
1    2000
2    1300
3     400
4     451
5      65
6     400
7     485
dtype: int64

In [70]:
data=pd.Series([1200,2000,1300,4500,451,65,])
print(data)
print(data.tail)
print(data.head)

0    1200
1    2000
2    1300
3    4500
4     451
5      65
dtype: int64
<bound method NDFrame.tail of 0    1200
1    2000
2    1300
3    4500
4     451
5      65
dtype: int64>
<bound method NDFrame.head of 0    1200
1    2000
2    1300
3    4500
4     451
5      65
dtype: int64>

In [79]:
data=pd.Series([1200,2000,1300,4500,451,65,])
ln=pd.Series(data+3)
ln

0    1203
1    2003
2    1303
3    4503
4     454
5      68
dtype: int64

In [87]:
data=pd.Series([1200,2000,1300,4500,451,65,])
print(data>1500)
print(data[data>1500])

0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool
1    2000
3    4500
dtype: int64

In [101]:
obj=pd.Series([1200,2000,1300,4500,451,65,],index=["b", "c", "e", "d", "a", "f"])
obj2=obj1.reindex(["a","b","c","e","d","a","f"])
obj2

a   NaN
b   NaN
c   NaN
e   NaN
d   NaN
a   NaN
f   NaN
dtype: float64

In [109]:
obj=pd.Series([1200,2000,1300,4500,451,65,])
obj.drop([3,5],inplace=True)
obj

0    1200
1    2000
2    1300
4     451
dtype: int64

In [134]:
df={"Name":["ron","tommy","aryan"],
                "age":[18,20,19],
                "address":["yc","cvh","jhb"]}
df1=pd.DataFrame(df)
df1

    Name  age address
0    ron   18      yc
1  tommy   20     cvh
2  aryan   19     jhb

In [120]:
s1=["shon",17]
s2=["ron",20]
s3=["tom",19]
s0=[s1,s2,s3]

df=pd.DataFrame(s0,columns=["Name","Age"])
df

   Name  Age
0  shon   17
1   ron   20
2   tom   19

In [154]:
data=pd.Series([1200,2000,1300,4500,451,65,48,485])
data[0::3]=400
data

0     400
1    2000
2    1300
3     400
4     451
5      65
6     400
7     485
dtype: int64

In [167]:
data= np.array([["ron",20,30],["tommy",19,30],["car",10,30]])
df=pd.DataFrame(data,columns=["Name","Age","age"])
print(df)
df[0:1]

    Name Age age
0    ron  20  30
1  tommy  19  30
2    car  10  30

  Name Age age
0  ron  20  30

In [186]:
s1=["shon",17]
s2=["ron",20]
s3=[None,19]
s0=[s1,s2,s3]

df=pd.DataFrame(s0,columns=["Name","Age"])
print(df)
print(df.dtypes)
print(df.size)
print(df.ndim)
print(df.T)
print(df.empty)
print(sum)
print(df.columns)
print(df.values)
print(df.index)

   Name  Age
0  shon   17
1   ron   20
2  None   19
Name    object
Age      int64
dtype: object
6
2
         0    1     2
Name  shon  ron  None
Age     17   20    19
False
<built-in function sum>
Index(['Name', 'Age'], dtype='object')
[['shon' 17]
 ['ron' 20]
 [None 19]]
RangeIndex(start=0, stop=3, step=1)

In [ ]:
df=pd.DataFrame({"Name":["ron","tommy","aryan"],
                "age":[18,20,19],
                "address":["yc","cvh","jhb"]})
print(df)
print(df["Name"])
print(df.age)

    Name  age address
0    ron   18      yc
1  tommy   20     cvh
2  aryan   19     jhb
0      ron
1    tommy
2    aryan
Name: Name, dtype: object
0      ron
1    tommy
2    aryan
Name: Name, dtype: object